---
title: "English mortality data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{English mortality data}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
bibliography: mort-refs.bib
header-includes:
  \usepackage{float}
  \usepackage{amsmath}
link-citations: yes
citation_package: natbib
biblio-style: vancouver
urlcolor: blue
---


```{r setup, include = FALSE, results = 'hide', warning = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.pos = 'H'
)

library(readxl)
library(data.table)
suppressPackageStartupMessages(library(ggplot2))
#library(cowplot)

#knitr::opts_knit$set(root.dir = "/Volumes/Shared/ScHARR/PR_STAPM/Code/R_packages/mort.tools")
#knitr::opts_knit$set(root.dir = "X:/ScHARR/PR_STAPM/Code/R_packages/mort.tools")

```

To inform the rates of mortality, we use Office for National Statistics mortality microdata. We use data from 2001 (being the first year for which estimates by Index of Multiple Deprivation quintile are available) to the latest available. We calculate and forecast mortality rates, and use lifetable methods to estimate the consequent years of life lost to death from each condition.    

### Death counts
Our death data for England are stratified as follows:  

- 326 lower tier Local Authorities    
- IMD quintiles   
- sex   
- Age groups single year of age then 90+  
- Disease categories defined by ICD-Codes   
- 2001-latest available   
- Death counts   

### Population counts
Our population data for England are mid-year population sizes:  

- 326 lower tier LAs   
- IMD quintiles   
- sex   
- Age groups single year of age then 90+   
- 2001-latest available   
- Population counts    

### Information governance
We abide by the [ScHARR information governance policy](https://www.sheffield.ac.uk/scharr/research/igov/policy00) and the terms of data access agreement. The data management plan is stored at `X:/ScHARR/PR_Mortality_data_TA/contracts/Information governance/Data management plan`.   

### Ethics
Ethics approval was received for "Investigation of the geographic and socioeconomic variation in alcohol and tobacco related mortality to inform decision support models for policy" from the School of Health and Related Research at the University of Sheffield with reference number 023092.    

