---
title: "Data check: Death rates in Scotland"
subtitle: "Sheffield Tobacco and Alcohol Policy Modelling"
link-citations: yes
# bibliography: refs/stapm_refs.bib
always_allow_html: yes
output:
  html_document:
    theme: flatly
    toc: true
    toc_float: true
    number_sections: true
---

<style>

body{
  font-family: 'Oxygen', sans-serif;
  font-size: 14px;
  line-height: 20px;
}

h1,h2,h3,h4 {
  font-family: 'Raleway', sans-serif;
  font-size: 24px;
}

.container { width: 1000px; }
h3 {
  background-color: #D4DAEC;
  #text-indent: 100px; 
}
h4 {
  text-indent: 100px;
}


g-table-intro h4 {
  text-indent: 0px;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(here))
#suppressPackageStartupMessages(library(hseclean))
```

[Click here to go to the Scottish mortality data page on the STAPM website](https://stapm.gitlab.io/mortality_data_scotland.html)

# Purpose

To plot the rates of death for each condition as part of the process of quality assurance of data inputs used in the STAPM modelling for Scotland.   

# Background

The data is supplied by National Records of Scotland as counts of deaths and mid-year population sizes for years 2008 to 2021. Counts of deaths are grouped into cause categories that match our [list of 85 causes related to tobacco and/or alcohol](https://stapm.gitlab.io/relative_risks.html), and "other causes". These data are processed to estimate the cause-specific central rates of death in one year intervals of age and period, stratified by sex and quintiles of the Index of Multiple Deprivation. 


# Description of the estimated death rates

There are 85 separate plots in each of the links below - one for each condition related to tobacco and/or alcohol. Rates are initially calculated for single years of age and period, sex and Index of Multiple Deprivation quintiles. For conditions with less than 10 deaths recorded in a year, the trend over data years is replaced with the average rate over all years of available data, i.e., where there is not enough information to describe the period trend, the average rate is used for all years. The rates calculated for single years of age and period are subsequently smoothed by calculating a moving average in a 7 x 3 dimension moving window of age and period, i.e. a moving average across 7 years of age and 3 data years. The rates presented in the plots correspond to the number of deaths per 100,000 people.    

* Coding practices seem to have changed in 2011 such that deaths were no longer coded as acute intoxication due to alcohol consumption.    

**Time trends in death rates by cause, sex and Index of Multiple Deprivation quintiles**   

Trends over data years in the rates are plotted for the period from 2008 to 2021. For plots of the time trends, the age dimension in the rates has been removed by calculating age-standardised rates using the 2019 population sizes in each population subgroup as weights, i.e., for each data year the population weighted average rate over ages 18 to 89 is calculated for each condition, sex and Index of Multiple Deprivation quintile.     

- <a href="https://stapm.gitlab.io/r-packages/mort.tools/articles/age_standardised_death_rates.html" target = "_blank" rel="noreferrer noopener">Time trends in death rates</a>   


**Age patterns in death rates by cause, sex and Index of Multiple Deprivation quintiles**     

Trends over age are plotted for a subsample of five data years from 2017 to 2021. The plots show the average age-specific rates across these five years for each condition, sex and Index of Multiple Deprivation quintile.    

- <a href="https://stapm.gitlab.io/r-packages/mort.tools/articles/age_specific_death_rates.html" target = "_blank" rel="noreferrer noopener">Age patterns in death rates</a>   


# Reproducibility notes

- Data processed using [mort.tools](https://stapm.github.io/mort.tools/) version `r packageDescription("mort.tools", fields = "Version")` (open access)
- Github code repository https://github.com/STAPM/mort.tools. Code for these plots https://github.com/STAPM/mort.tools/tree/master/vignettes/Scotland_mortality_calculations
- Open Science Framework repository https://osf.io/wn6rh/


<!-- # References -->





















































